## Aula 6: Machine Learning: aprendizado de máquina supervisionado

In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets

/home/jose/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/jose/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/jose/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
iris = datasets.load_iris()

In [4]:
df_iris = pd.DataFrame(iris.data)
df_iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df_iris['target'] = iris.target

df_iris.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [5]:
# Preparando os dados para o treinamento e previsão
X = df_iris.drop(['target'], axis=1)
y = df_iris['target']

### Classificação com árvore de decisão

In [6]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=4,
    criterion='entropy',
    random_state=1
)


model.fit(
    X, y
)


print('.predict(X):\n')
print(model.predict(X))

.predict(X):

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
print('\n\n.predict_proba(X):')

## Prevê a probabilidade de cada entrada em relação a cada classe
model.predict_proba(X)



.predict_proba(X):


array([[1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.

In [8]:
from sklearn.tree import export_graphviz
from subprocess import call
from IPython.display import Image


export_graphviz(
    model,
    out_file='./img/tree.dot',
    feature_names=X.columns,
    class_names='target'
)

In [9]:
X_regressao = df_iris.drop(['target', 'petal_length'], axis=1)
y_regressao = df_iris['petal_length']

In [10]:
from sklearn.tree import DecisionTreeRegressor

model_regressao = DecisionTreeRegressor(
    max_depth=4,
    criterion='mse',
    random_state=1
)


model_regressao.fit(
    X_regressao, y_regressao
)


print('.predict(X):\n')
print(model_regressao.predict(X_regressao))

.predict(X):

[1.48064516 1.48064516 1.48064516 1.37142857 1.48064516 1.5
 1.37142857 1.48064516 1.37142857 1.48064516 1.48064516 1.48064516
 1.48064516 1.1        1.2        1.5        1.5        1.48064516
 1.48064516 1.48064516 1.48064516 1.66       1.         1.66
 1.48064516 1.48064516 1.66       1.48064516 1.48064516 1.48064516
 1.48064516 1.5        1.48064516 1.48064516 1.48064516 1.48064516
 1.48064516 1.48064516 1.37142857 1.48064516 1.48064516 1.37142857
 1.37142857 1.66       1.66       1.48064516 1.48064516 1.37142857
 1.48064516 1.48064516 4.74375    4.74375    4.74375    4.06190476
 4.74375    4.06190476 5.05217391 3.275      4.32857143 4.06190476
 3.275      4.06190476 4.32857143 4.74375    4.06190476 4.74375
 4.06190476 4.06190476 4.74375    4.06190476 5.05217391 4.32857143
 4.74375    4.32857143 4.32857143 4.74375    4.74375    5.05217391
 4.74375    4.06190476 4.06190476 4.06190476 4.06190476 5.05217391
 4.06190476 5.05217391 4.74375    4.32857143 4.06190476 4.061904

In [11]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=1
)

In [13]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

X_train.head()

(100, 4) (100,)
(50, 4) (50,)


sepal_length  sepal_width  petal_length  petal_width
39            5.1          3.4           1.5          0.2
36            5.5          3.5           1.3          0.2
117           7.7          3.8           6.7          2.2
139           6.9          3.1           5.4          2.1
107           7.3          2.9           6.3          1.8

In [14]:
model = DecisionTreeClassifier(
    max_depth=4,
    criterion='entropy',
    random_state=1
)

model.fit(
    X_train, y_train
)

y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1])

In [15]:
metrics.accuracy_score(
    y_test,
    y_pred
)

0.96

In [16]:
metrics.f1_score(
    y_test,
    y_pred,
    average=None
)

array([1.        , 0.94736842, 0.92857143])

### Matriz de confusão

- Permite visualizar as previsões corretas e incorretas para cada classe
- Quanto maiores os valores da diagonal, mais corretas as previsões

In [17]:
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt

conf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print('Matriz de confusão:\n', conf_mat)

labels = iris.target_names.tolist()
fig = plt.figure()
ax = fig.add_subplot(111)
cax = ax.matshow(conf_mat, cmap=plt.cm.Blues)
fig.colorbar(cax)
ax.set_xticklabels([''] + labels)
ax.set_yticklabels([''] + labels)
plt.xlabel('Predicted')
plt.ylabel('Expected')
plt.show()

Matriz de confusão:
 [[17  0  0]
 [ 0 18  1]
 [ 0  1 13]]


<Figure size 640x480 with 2 Axes>

In [18]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model, 
    X,
    y,
    cv=3,
    scoring='accuracy',
    n_jobs=1
)

print('Score de cada fold', scores)
print('Acurácia média: ', np.mean(scores))
print('Desvio padrão: ', np.std(scores))

Score de cada fold [0.98039216 0.92156863 0.97916667]
Acurácia média:  0.960375816993464
Desvio padrão:  0.027445387307583054


In [19]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

model = RandomForestClassifier(
    max_depth=4,
    n_estimators=25,
    n_jobs=-1,
    random_state=1
)

model.fit(
    X_train, y_train
)

model.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1])

In [20]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.preprocessing import *


std = StandardScaler()
std.fit(X_train)

X_train = std.transform(X_train)
X_test = std.transform(X_test)

model = MLPClassifier(
    hidden_layer_sizes=(50,15),
    activation='tanh',
    max_iter=500,
    random_state=1
)

model.fit(
    X_train, y_train
)

model.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 2, 0, 0, 0, 1])

In [22]:
from sklearn.svm import SVC, SVR

model = SVC(
    kernel='rbf',
    C=1.0, # Parâmetro de penalidade de erro
    random_state=1
)

model.fit(
    X_train, y_train
)

model.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1])

In [23]:
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

model = KNeighborsClassifier(
    n_neighbors=3,
    n_jobs=-1
)

model.fit(
    X_train, y_train
)

model.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1])

In [27]:
from xgboost import XGBClassifier, XGBRegressor

model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    n_jobs=-1,
    random_state=1,
    gamma=1
)

model.fit(
    X_train, y_train
)

model.predict(X_test)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 2, 0, 0, 0, 1])